### ISSUE TITLE
Using a webui commit after Dec 9, 2022 breaks it

### ISSUE THREAD

**Issue by Luke2642** [antis0007/sd-webui-multiple-hypernetworks#4]
The latest commits on the webui have broken it. Line 289 of the script throws an index error.

Multiple hypernetworks still works if you cmd to your stable-diffusion-webui folder, cmd and roll back to an earlier commit from the 9th of December:

git checkout 9539c2045a2de9e900b96acbf67e41fafe93c6f6

**Comment by antis0007** [comment]
@Luke2642 Thanks for reporting this! I looked into this for a few hours earlier today and couldn't understand for the life of me what broke in this update. Tried git checkout on various commits to the repo and everything seemed to break for me even worse. Not sure what happened here but it seems some sequence of git commits broke the webui for me. 

I ultimately ended up moving all my scripts/models/extra stuff over to a fresh install of the repo and everything worked flawlessly (and surprisingly much faster after a fresh install). I know this isn't a perfect solution but if you have the time, try using the latest version of the script in a fresh install of the webui and let me know if it still has errors. There have been changes to certain relevant functions for this script so I'll upload a new version to match the latest ui soon (have a personal occasion tonight, may be tomorrow). Thanks!

**Comment by DarkAlchy** [comment]
Mine works, and I am up to date it says with a git pull BUT it is locked in and the reset didn't work so I had to remove it completely.  I am rolling back because RESET did work before.

**Comment by DarkAlchy** [comment]
> @Luke2642 Thanks for reporting this! I looked into this for a few hours earlier today and couldn't understand for the life of me what broke in this update. Tried git checkout on various commits to the repo and everything seemed to break for me even worse. Not sure what happened here but it seems some sequence of git commits broke the webui for me.
> 
> I ultimately ended up moving all my scripts/models/extra stuff over to a fresh install of the repo and everything worked flawlessly (and surprisingly much faster after a fresh install). I know this isn't a perfect solution but if you have the time, try using the latest version of the script in a fresh install of the webui and let me know if it still has errors. There have been changes to certain relevant functions for this script so I'll upload a new version to match the latest ui soon (have a personal occasion tonight, may be tomorrow). Thanks!

I have had to reinstall webui more times than one can imagine and it always starts out superfast and soon will be sluggish even loading up (from instantly to 10-15s).

**Comment by antis0007** [comment]
> Mine works, and I am up to date it says with a git pull BUT it is locked in and the reset didn't work so I had to remove it completely. I am rolling back because RESET did work before.

sorry, that was a bug I introduced in one version accidentally. Was trying to make it appear on all panes by default but it broke some of the script functionality so I think I did a commit immediately after that to fix it.
