### ISSUE TITLE
Reset no longer works

### ISSUE THREAD

**Issue by DarkAlchy** [antis0007/sd-webui-multiple-hypernetworks#6]
If I want to go back to just one hyper reset no longer works as I reset and nothing changes.  If I clear the boxes (with or without hitting reset) it errors Automatic1111 the next generation I try (which relates to this script not getting out of the way).

**Comment by antis0007** [comment]
@DarkAlchy last final exam tomorrow but ill get to helping you with this soon
The reset button isn't meant to reset the hypernetwork textboxes (though I can look into doing that), its meant to unload the hypernetworks, unhijack the functions and reload your main model. It stops the generations from glitching once you're done using the script.

**Comment by DarkAlchy** [comment]
> @DarkAlchy last final exam tomorrow but ill get to helping you with this soon The reset button isn't meant to reset the hypernetwork textboxes (though I can look into doing that), its meant to unload the hypernetworks, unhijack the functions and reload your main model. It stops the generations from glitching once you're done using the script.

Which is precisely what it is no longer doing.  It hijacks and stays hijacking it is what I was saying.

**Comment by antis0007** [comment]
I believe this is fixed in the latest version
