### ISSUE TITLE
Hypernetwork strengths from script not work

### ISSUE THREAD

**Issue by bananasss00** [antis0007/sd-webui-multiple-hypernetworks#8]
The script generates the same images, with different parameter strength values

But if you change the strength of the hypernetwork in the global settings of the webui, then the pictures are already generated differently, i.e. global value is used for all hypernetworks

**update:**
My mistake. it's conflict with extension https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension

**Comment by antis0007** [comment]
Really appreciate you bringing this to light, and your subsequent patch! I've been a bit busier than I thought these holidays so I haven't had much time to improve this script. Hoping to add some cool features in future versions though.
